name: test

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master,main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
          api_key: ${{ secrets.API_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
      run: base_url=https://sandbox-api.iyzipay.com cargo test -- --skip sample