name: test

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master,main ]

env:
  CARGO_TERM_COLOR: always
  api_key: ${{ secrets.API_KEY }}
  secret_key: ${{ secrets.SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: base_url=https://sandbox-api.iyzipay.com cargo test -- --skip sample