name: test

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master,main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
          API_KEY: ${{ secrets.API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run:  api_key=""$env:API_KEY"" secret_key=""$env:SECRET_KEY"" base_url=https://sandbox-api.iyzipay.com cargo test -- --skip sample