name: test

on:
  push:
    branches: "**"
  pull_request:
    branches: [ master,main ]

env:
  CARGO_TERM_COLOR: always
  API_KEY: ${{ secrets.API_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  BASE_URL: https://sandbox-api.iyzipay.com 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --skip sample